### Import Libraries

In [ ]:
import pandas as pd
!pip install pymysql

Requirement already satisfied: pymysql in /usr/local/lib/python3.11/dist-packages (1.1.1)

In [ ]:
from sqlalchemy import create_engine
import pymysql

### 1. Extract Data

1.1 Enrollies' data

In [ ]:
google_sheet_id = '1VCkHwBjJGRJ21asd9pxW4_0z2PWuKhbLR3gUHm-p4GI'
url = 'https://docs.google.com/spreadsheets/d/'+ google_sheet_id+ '/export?format=xlsx'
enrollies_data = pd.read_excel(url, sheet_name = 'enrollies')

In [ ]:
enrollies_data.head()

   enrollee_id      full_name      city gender
0         8949     Mike Jones  city_103   Male
1        29725    Laura Jones   city_40   Male
2        11561   David Miller   city_21    NaN
3        33241    Laura Davis  city_115    NaN
4          666  Alex Martinez  city_162   Male

### 1.2 Enrollies' education

In [ ]:
enrollies_education = pd.read_excel('/content/enrollies_education (1).xlsx')
enrollies_education

       enrollee_id enrolled_university education_level major_discipline
0             8949       no_enrollment        Graduate             STEM
1            29725       no_enrollment        Graduate             STEM
2            11561    Full time course        Graduate             STEM
3            33241                 NaN        Graduate  Business Degree
4              666       no_enrollment         Masters             STEM
...            ...                 ...             ...              ...
19153         7386       no_enrollment        Graduate       Humanities
19154        31398       no_enrollment        Graduate             STEM
19155        24576       no_enrollment        Graduate             STEM
19156         5756       no_enrollment     High School              NaN
19157        23834       no_enrollment  Primary School              NaN

[19158 rows x 4 columns]

### 1.3 Enrollies' working experience

In [ ]:
work_experience = pd.read_csv('/content/work_experience (1).csv')
work_experience

,enrollee_id,relevent_experience,experience,company_size,company_type,last_new_job
0,8949,Has relevent experience,>20,NaN,NaN,1
1,29725,No relevent experience,15,50-99,Pvt Ltd,>4
2,11561,No relevent experience,5,NaN,NaN,never
3,33241,No relevent experience,<1,NaN,Pvt Ltd,never
4,666,Has relevent experience,>20,50-99,Funded Startup,4
...,...,...,...,...,...,...
19153,7386,No relevent experience,14,NaN,NaN,1
19154,31398,Has relevent experience,14,NaN,NaN,4
19155,24576,Has relevent experience,>20,50-99,Pvt Ltd,4
19156,5756,Has relevent experience,<1,500-999,Pvt Ltd,2
19157,23834,No relevent experience,2,NaN,NaN,1

### 1.4 Training hours

In [ ]:
engine = create_engine('mysql+pymysql://etl_practice:550814@112.213.86.31:3360/company_course')
training_hours = pd.read_sql_table('training_hours', engine)

In [ ]:
training_hours.head()

   enrollee_id  training_hours
0         8949              36
1        29725              47
2        11561              83
3        33241              52
4          666               8

### 1.5 City development index

In [ ]:
table = pd.read_html('https://sca-programming-school.github.io/city_development_index/index.html')
cities = table[0]

In [ ]:
cities.head()

       City  City Development Index
0  city_103                   0.920
1   city_40                   0.776
2   city_21                   0.624
3  city_115                   0.789
4  city_162                   0.767

### 1.6 Employment

In [ ]:
employment = pd.read_sql_table('employment',engine)

In [ ]:
employment.head()

   enrollee_id  employed
0            1       0.0
1            2       1.0
2            4       0.0
3            5       0.0
4            7       0.0

### 2.Transform Data

2.1 Enrollies' Data

In [ ]:
enrollies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   enrollee_id  19158 non-null  int64
 1   full_name    19158 non-null  object
 2   city         19158 non-null  object
 3   gender       14650 non-null  object
dtypes: int64(1), object(3)
memory usage: 598.8+ KB

### Fix data type

In [ ]:
enrollies_data['full_name'] = enrollies_data['full_name'].astype('string')

In [ ]:
enrollies_data['city'] = enrollies_data['city'].astype('category')
enrollies_data['gender'] = enrollies_data['gender'].astype('category')

### Fill Missing Value

In [ ]:
gender_mode = enrollies_data['gender'].mode()[0]
enrollies_data['gender'] = enrollies_data['gender'].fillna(gender_mode)

In [ ]:
enrollies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   enrollee_id  19158 non-null  int64
 1   full_name    19158 non-null  string
 2   city         19158 non-null  category
 3   gender       19158 non-null  category
dtypes: category(2), int64(1), string(1)
memory usage: 342.1 KB

###2.2 enrollies_education

In [ ]:
enrollies_education.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   enrolled_university  18772 non-null  object
 2   education_level      18698 non-null  object
 3   major_discipline     16345 non-null  object
dtypes: int64(1), object(3)
memory usage: 598.8+ KB

### Fix data type

In [ ]:
enrollies_education['enrolled_university'] = enrollies_education['enrolled_university'].astype('string')
enrollies_education['education_level'] = enrollies_education['education_level'].astype('category')
enrollies_education['major_discipline'] = enrollies_education['major_discipline'].astype('string')

###Fill Missing Value

In [ ]:
enrollies_education['enrolled_university'] = enrolled_university.fillna('no_enrollment')
enrollies_education['major_discipline'] = major_discipline.fillna('No Major')
education_level_mode = enrollies_education['education_level'].mode()[0]
enrollies_education['education_level'] = enrollies_education['education_level'].fillna(education_level_mode)

In [ ]:
enrollies_education.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   enrolled_university  19158 non-null  string
 2   education_level      19158 non-null  category
 3   major_discipline     19158 non-null  string
dtypes: category(1), int64(1), string(2)
memory usage: 468.1 KB

### 2.3 Work_experience

In [ ]:
work_experience.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   relevent_experience  19158 non-null  object
 2   experience           19093 non-null  object
 3   company_size         13220 non-null  object
 4   company_type         13018 non-null  object
 5   last_new_job         18735 non-null  object
dtypes: int64(1), object(5)
memory usage: 898.2+ KB

### Fix data type

In [ ]:
work_experience['relevent_experience'] = work_experience['relevent_experience'].astype('category')
work_experience['experience'] = work_experience['experience'].astype('category')
work_experience['company_size'] = work_experience['company_size'].astype('category')
work_experience['company_type'] = work_experience['company_type'].astype('category')
work_experience['last_new_job'] = work_experience['last_new_job'].astype('category')

### Fill Missing Value

In [ ]:
experience = work_experience['experience'].mode()[0]
work_experience['experience'] = work_experience['experience'].fillna(experience)
company_size = work_experience['company_size'].mode()[0]
work_experience['company_size'] = work_experience['company_size'].fillna(company_size)
company_type = work_experience['company_type'].mode()[0]
work_experience['company_type'] = work_experience['company_type'].fillna(company_type)
last_new_job = work_experience['last_new_job'].mode()[0]
work_experience['last_new_job'] = work_experience['last_new_job'].fillna(last_new_job)

In [ ]:
work_experience.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   relevent_experience  19158 non-null  category
 2   experience           19158 non-null  category
 3   company_size         19158 non-null  category
 4   company_type         19158 non-null  category
 5   last_new_job         19158 non-null  category
dtypes: category(5), int64(1)
memory usage: 245.0 KB

### 2.4 Training_hours

In [ ]:
training_hours.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   enrollee_id     19158 non-null  int64
 1   training_hours  19158 non-null  int64
dtypes: int64(2)
memory usage: 299.5 KB

### 2.5 Cities

In [ ]:
cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   City                    123 non-null    object
 1   City Development Index  123 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.1+ KB

### Fix Data Type

In [ ]:
cities['City'] = cities['City'].astype('string')

In [ ]:
cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   City                    123 non-null    string
 1   City Development Index  123 non-null    float64
dtypes: float64(1), string(1)
memory usage: 2.1 KB

### 2.6 Employment

In [ ]:
employment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   enrollee_id  19158 non-null  int64
 1   employed     19158 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 299.5 KB

# Load Data

### Manually Inserting DataFrames into SQLite

In [ ]:
db_path = 'data_warehouse.db'
engine = create_engine(f'sqlite:///{db_path}')
enrollies_data.to_sql('dim_enrollies_data', engine, if_exists = 'replace', index = False)
enrollies_education.to_sql('fact_enrollies_education', engine, if_exists = 'replace', index = False)
work_experience.to_sql('dim_work_experience', engine, if_exists = 'replace', index = False)
cities.to_sql('dim_cities', engine, if_exists = 'replace', index = False)
employment.to_sql('dim_enrollies', engine, if_exists = 'replace', index = False)

19158

### Refactoring DataFrame to SQL Insertion with SQLAlchemy

In [ ]:
from sqlalchemy import create_engine

def save_to_sql(tables, db_path='data_warehouse.db'):
    engine = create_engine(f'sqlite:///{db_path}')
    for df, table_name in tables:
        df.to_sql(table_name, engine, if_exists='replace', index=False)

tables_to_save = [
    (enrollies_data, 'dim_enrollies_data'),
    (enrollies_education, 'dim_enrollies_education'),
    (work_experience, 'dim_work_experience'),
    (cities, 'dim_cities'),
    (employment, 'fact_enrollies')
]

save_to_sql(tables_to_save)